# Generated by Django 4.2.10 on 2024-02-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_de_lancamento', models.IntegerField()),
                ('diretor', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
            ],
        ),
    ]
